### ISSUE TITLE
Documentation for RVsharing

### ISSUE THREAD

**Issue by syounkin** [syounkin/RVsharing#1]
Edit the file RVsharing.Rd in the man directory.  Currently it uses comments from the source code.

Making the edit and pushing the changes will be a useful exercise to learn git and github.

It will also help me to understand the function better.

**Comment by abureau** [comment]
I edited the documentation of RVsharing based on what I understand of the Rd format.

I realized that what I called an "intermediate ancestor" in the comments is called a "branching individual" in the methods manuscript. I changed to "branching individual" in the documentation for consistency.

I am not sure what "format unknown" means for the arguments. I did not change it.
